### ISSUE TITLE
Debian stretch: additional package is needed for installation. 

### ISSUE THREAD

**Issue by koenwybo** [riverrun/genxword#10]
Hi riverrun, 

Installing genxword on debian stretch with the command 
**pip3 install genxword**
failed. The packages listed on  https://github.com/riverrun/genxword#dependencies were all installed. 
There is an additional package to be installed on debian stretch: gettext. 
**apt-get install gettext**
After this, installation worked.

**Comment by riverrun** [comment]
Thanks for letting me know. I'll update the README about this.

**Comment by riverrun** [comment]
Updated README in #296
