### ISSUE TITLE
pypi packages out of date

### ISSUE THREAD

**Issue by cslycord** [riverrun/genxword#15]
The latest version available on pypi/pip is 1.2.0, where the current version is 2.0.0.

Also, the description on here mentions the gettext dependency whereas the description in pypi has it missing like it used to on here.

Thanks

**Comment by riverrun** [comment]
Thanks for letting me know. I will look into it and get back to you soon.

**Comment by riverrun** [comment]
Sorry about the delay - finally uploaded version 2.0.0 today.
