### ISSUE TITLE
pip3 install fails with error referring to french PO file

### ISSUE THREAD

**Issue by worldwidelexicon** [riverrun/genxword#19]
When I run pip3 install genxword, it fails with an error message referring to the French PO/MO file. See error log below:

    Complete output (33 lines):
    /bin/sh: msgfmt: command not found
    /bin/sh: msgfmt: command not found
    /bin/sh: msgfmt: command not found
    /bin/sh: msgfmt: command not found
    /bin/sh: msgfmt: command not found
    /bin/sh: msgfmt: command not found
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/genxword
    copying genxword/complexstring2.py -> build/lib/genxword
    copying genxword/complexstring.py -> build/lib/genxword
    copying genxword/calculate.py -> build/lib/genxword
    copying genxword/control.py -> build/lib/genxword
    copying genxword/__init__.py -> build/lib/genxword
    copying genxword/cli.py -> build/lib/genxword
    copying genxword/gui.py -> build/lib/genxword
    running egg_info
    writing genxword.egg-info/PKG-INFO
    writing dependency_links to genxword.egg-info/dependency_links.txt
    writing entry points to genxword.egg-info/entry_points.txt
    writing top-level names to genxword.egg-info/top_level.txt
    reading manifest file 'genxword.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'genxword.egg-info/SOURCES.txt'
    creating build/lib/genxword/data
    copying genxword/data/gumby.lang -> build/lib/genxword/data
    copying genxword/data/help_page -> build/lib/genxword/data
    running install_lib
    running install_data
    error: can't copy 'mo/fr/genxword.mo': doesn't exist or not a regular file

**Comment by riverrun** [comment]
I updated the package today. Could you try downloading it again and see if it works now?

**Comment by cslycord** [comment]
Maybe I am off-base, but if you're getting:
`msgfmt: command not found`
that seems like you're missing one or more of gettext, gettext-dev, and/or gettext-devel packages.

**Comment by riverrun** [comment]
Well noticed :)

And that's why the 'mo/fr/genxword.mo' is not created (does not exist).

@worldwidelexicon closing this issue for now. If you have any further comments / question, just let me know.
