### ISSUE TITLE
2.0.1 release not released on github

### ISSUE THREAD

**Issue by cslycord** [riverrun/genxword#20]
Seems the 2.0.1 release was only released to pypi. On here, github, the most recent release is 2.0.0

I only noticed it because I wrote a gentoo ebuild that would download the sourcecode from github and when I changed it to 2.0.1, it couldn't find the sources.

Note: I fixed the ebuild I was working on by pointing it to the source code uploaded to pypi, so this is more an FYI than anything.

**Comment by riverrun** [comment]
Thanks for pointing that out. I have just updated it.
